version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=admin
      - DB_PASSWORD=suasenha
      - DB_NAME=chave_serpentes
    # O comando abaixo força o gunicorn a esperar mais tempo se o Codespaces travar a requisição
    command: gunicorn --bind 0.0.0.0:8080 --timeout 120 seu_projeto.wsgi:application
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=suasenha
      - POSTGRES_DB=chave_serpentes
    # REMOVEMOS as portas daqui para o Codespaces não tentar "ler" o banco de dados como site
    volumes:
      - postgres_data:/var/lib/postgresql/data
